<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About - PokeMMO Shiny OT Leaderboard</title>
    <link rel="icon" type="image/png" href="icon.png">
    <?php include 'styles-scripts.php'; ?>
</head>
<body>
    <?php include 'nav.php'; ?>
    <div class="container">
        <h1>About PokeMMO Shiny OT Leaderboard</h1>
        <p>The PokeMMO Shiny OT Leaderboard is created by <a href="https://pokemmo.zone/" target="_blank">PokeMMO Zone</a>. It ranks teams and individual players based on their shiny Pokémon achievements. Our goal is to create a friendly competition and encourage players to strive for excellence in catching shiny Pokémon. Only OT (Original Trainer) shinies are counted, meaning these are shinies the players have caught themselves and still possess.</p>
        <h2>How It Works</h2>
        <p>The leaderboard is generated by collecting data through web scraping. Teams often have a shiny showcase, and the data is scraped from there.</p>
        <h2>Data Sources</h2>
        <p>The shiny counts are updated on a daily basis from publicly available information on PokeMMO. This ensures that our leaderboard reflects the most current and accurate information.</p>
        <h2>Brought to You By</h2>
        <p>This website is brought to you by <a href="https://pokemmo.zone/" target="_blank">PokeMMO Zone</a>.</p>
        <h2>Contact Us</h2>
        <p>If you have any questions or feedback, you can create a support ticket on the <a href="http://discord.pokemmo.zone/" target="_blank">PokeMMO Zone discord</a> or submit pull requests to our repository at <a href="https://github.com/PokeMMOZone/shiny-leaderboard" target="_blank">https://github.com/PokeMMOZone/shiny-leaderboard</a>.</p>
    </div>
    <?php include 'footer.php'; ?>
</body>
</html>
